### ISSUE TITLE
StickerSelector improvements

### ISSUE THREAD

**Issue by nikgraf** [nikgraf/react-unicorn-editor#20]
- [x] prevent scrolling the page inside the popover
- [x] add subtle white gradient/shadow at the bottom to indicate people can scroll

**Comment by mxstbr** [comment]
Add `overflow: hidden` to `body` on hover over the `StickerSelector` for the first point.

**Comment by mxstbr** [comment]
I added the gradient in 39fdc78, but I don't think it's very nice – I'd say we remove it again, the scrollbar is enough to know that one can scroll.
